data_prep:
  models: [
    "efficientdet"
    ]
  data_subdirs_paths:
    - "/polyaxon-v1-data/workspaces/jannah/data/life3-aut0/20220224_1032621/images 1-7 revised"
    - "/polyaxon-v1-data/workspaces/jannah/data/life3-aut0/20220224_1032621/images 8-24 revised"
    - "/polyaxon-v1-data/workspaces/jannah/data/life3-aut0/20220224_1032621/images 25-35 revised"
    - "/polyaxon-v1-data/workspaces/jannah/data/life3-aut0/20220224_1032621/images 36-55 revised"
    - "/polyaxon-v1-data/workspaces/jannah/data/life3-aut0/20220224_1032621/images 56-75 revised"
    - "/polyaxon-v1-data/workspaces/jannah/data/life3-aut0/20220224_1032621/images 76-100 revised"
  raw_data_path: "/polyaxon-v1-data/workspaces/jannah/data/raw"
  processed_data_path: "/polyaxon-v1-data/workspaces/jannah/data/processed"
  interim_data_path: "/polyaxon-v1-data/workspaces/jannah/data/interim"
  annotations_subdir: "annotations"
  images_subdir: "images"
  coco_annotations_filename: "instances_default.json"
  combined_annotations_filename: "annotations_all.csv"
  excluded_images:
    - "1 c0.7L d5 20x undilut OD15.jpg"
    - "3 c10L d10 20x undilut OD8.jpg"
  class_map: {
        'cell': 0,
        'cell accumulation': 1
    }
  remap_classes: True
  class_remapping: {
    'Cells': 'cell',
    'cell accumulation (small cells)': 'cell accumulation',
    'cell accumulation (large cells)': 'cell accumulation'
    }
  accepted_image_formats: ['jpg', 'JPG', 'jpeg', 'png']
  # Tile/slice processed images
  run_tiling: True
  tile_coco_filter_categories:
    - "Cells"
    - "cell accumulation (small cells)"
    - "cell accumulation (large cells)"
  tile_data_dir_paths: "/polyaxon-v1-data/workspaces/jannah/data/processed/tiled_640"
  tile_slice_height : 640
  tile_slice_width : 640
  tile_overlap_height_ratio : 0.2
  tile_overlap_width_ratio : 0.2
  tile_ignore_negative_samples : False # If True, images without annotations are ignored
  # Data Split
  target_col: 'category_name'
  save_data_splits: True
  val_size: 0.1 # The proportion of data allocated to the validation set, based ongit  the proportion of the overall data
  test_size: 0.2  # The proportion of data allocated to the test set, based on the proportion of the overall data
  train_base_filename: 'annotations_train.csv'
  validation_base_filename: 'annotations_validation.csv'
  test_base_filename: 'annotations_test.csv'
  meta_data_filename: '/polyaxon-v1-data/workspaces/jannah/data/Metadata list for AI Singapore final.xlsx'
  stratify_column: 'incubation_day'  # option: 'incubation_day' or 'dilution_factor' or 'incub_day_dilu_fact' or None. Note: 'incub_day_dilu_fact' not suitable without tiling

train:
  load_data: False
  model_name: "efficientdet"
  setup_mlflow: false
  mlflow_autolog: false
  mlflow_tracking_uri: "mlflow-nginx-server-svc.polyaxon-v1.svc.local"
  mlflow_exp_name: "life3-biotech"
  mlflow_artifact_location: "gs://life3-biotech-artifacts/mlflow-tracking-server"
  save_weights_only: True
  lr_scheduler: "reduce_on_plateau"
  initial_lr: 0.00001
  # LR parameters for reduce on plateau
  lr_reduce_factor: 0.1
  lr_reduce_patience: 2
  lr_min_delta: 0.01
  # Augmentation
  run_data_augmentation: False
  save_augmented_images: False
  early_stopping: True
  eval_only: False
  patience: 20
  # Non-maximum suppression params
  run_nms: True
  nms_threshold: 0.5
  score_threshold: 0.05
  # Evaluation params
  eval_batch_size: 8
  eval_iou_threshold: [0.5]
  eval_score_threshold: 0.01

train_augmentation:
  aug_seed: 42

inference:
  model_path: "/polyaxon-v1-data/workspaces/jannah/models/efficientdet_b0_20220414_110244.h5"
  input_path: "/polyaxon-v1-data/workspaces/jannah/data/inference/input"
  save_output_image: True
  output_path: "/polyaxon-v1-data/workspaces/jannah/data/inference/output"
  confidence_threshold: 0.75
  efficientdet_config: {
      "model_type": 0,
      "score_threshold": 0.5,
      "detect_ids": [0],
  }
  draw_bbox_config: {
    "show_labels":True
  }

efficientdet:
    train_annotations_path: '/polyaxon-v1-data/workspaces/jannah/data/processed/annotations_train_efficientdet_b0.csv'
    val_annotations_path: '/polyaxon-v1-data/workspaces/jannah/data/processed/annotations_val_efficientdet_b0.csv'
    test_annotations_path: '/polyaxon-v1-data/workspaces/jannah/data/processed/annotations_test_efficientdet_b0.csv'
    saved_best_model: '' # model file must exist in directory referenced in snapshot-path below
    snapshot-path: '/polyaxon-v1-data/workspaces/jannah/models/'
    gpu: 0
    train_backbone: 0
    snapshot: 'imagenet'
    weighted-bifpn: True
    freeze-bn: False
    freeze-backbone: False
    random-transform: False
    batch_size: 8
    epochs: 50
    steps: 128
    inference_backbone: 0
    inference_model_path: ''
    inference_confidence_cutoff: 0.75
    # parameters for anchor boxes
    anchor_box_ratios: [1, 0.5, 2] # [0.403, 1.0, 2.479]
    anchor_box_scales: [0.5, 1.0, 2.0] # [0.4, 0.496, 0.625]
    image_sizes: [512, 640, 768, 896, 1024, 1280, 1408]
  