data_prep:
  models: [
    "efficientdet"
    ]
  data_subdirs_paths:
    - "/Users/dylanpoh/Documents/AIsingapore/GitHub/data/life3-aut0/20220224_1032621/images 1-7 revised"
    - "/Users/dylanpoh/Documents/AIsingapore/GitHub/data/life3-aut0/20220224_1032621/images 8-24 revised"
    - "/Users/dylanpoh/Documents/AIsingapore/GitHub/data/life3-aut0/20220224_1032621/images 25-35 revised"
    - "/Users/dylanpoh/Documents/AIsingapore/GitHub/data/life3-aut0/20220224_1032621/images 36-55 revised"
    - "/Users/dylanpoh/Documents/AIsingapore/GitHub/data/life3-aut0/20220224_1032621/images 56-75 revised"
    - "/Users/dylanpoh/Documents/AIsingapore/GitHub/data/life3-aut0/20220224_1032621/images 76-100 revised"
  raw_data_path: "/users/dylanpoh/documents/aisingapore/github/data/raw"
  processed_data_path: "/users/dylanpoh/documents/aisingapore/github/data/processed"
  interim_data_path: "/users/dylanpoh/documents/aisingapore/github/data/interim"
  annotations_subdir: "annotations"
  images_subdir: "images"
  coco_annotations_filename: "instances_default.json"
  combined_annotations_filename: "annotations_all.csv"
  excluded_images:
    - "1 c0.7L d5 20x undilut OD15.jpg"
    - "3 c10L d10 20x undilut OD8.jpg"
  class_map: {
        'cell': 0,
        'cell accumulation': 1
    }
  remap_classes: True
  class_remapping: {
    'Cells': 'cell',
    'cell accumulation (small cells)': 'cell accumulation',
    'cell accumulation (large cells)': 'cell accumulation'
    }
  accepted_image_formats: ['jpg', 'JPG', 'jpeg', 'png']
  # Tile/slice processed images
  run_tiling: False
  tile_coco_filter_categories:
    - "Cells"
    - "cell accumulation (small cells)"
    - "cell accumulation (large cells)"
  tile_data_dir_paths: "/users/dylanpoh/documents/aisingapore/github/data/tile_processed"
  tile_slice_height : 640
  tile_slice_width : 640
  tile_overlap_height_ratio : 0.2
  tile_overlap_width_ratio : 0.2
  tile_ignore_negative_samples : False # If True, images without annotations are ignored
  # Data Split
  target_col: 'category_name'
  save_data_splits: True
  val_size: 0.1 # The proportion of data allocated to the validation set, based on the proportion of the overall data
  test_size: 0.2  # The proportion of data allocated to the test set, based on the proportion of the overall data
  train_base_filename: 'annotations_train.csv'
  validation_base_filename: 'annotations_validation.csv'
  test_base_filename: 'annotations_test.csv'
  meta_data_filename: '/Users/dylanpoh/Documents/AIsingapore/GitHub/data/Metadata list for AI Singapore final.xlsx'
  stratify_column: 'incubation_day'  # option: 'incubation_day' or 'dilution_factor' or 'incub_day_dilu_fact' or None

train:
  load_data: True
  model_name: "efficientdet"
  setup_mlflow: false
  mlflow_autolog: false
  mlflow_tracking_uri: "mlflow-nginx-server-svc.polyaxon-v1.svc.local"
  mlflow_exp_name: "life3-biotech"
  mlflow_artifact_location: "gs://life3-biotech-artifacts/mlflow-tracking-server"
  data_path: "../life3-biotech-data/processed/subdir"
  seed: 4002
  optimiser: "adam"
  metric: "accuracy"
  lr_scheduler: "reduce_on_plateau"
  initial_lr: 0.001
  # LR parameters for reduce on plateau
  lr_reduce_factor: 0.1
  lr_reduce_patience: 2
  lr_min_delta: 0.01
  # Augmentation
  run_data_augmentation: False
  save_augmented_images: False
  early_stopping: True
  eval_only: False
  patience: 20
  # Non-maximum suppression params
  run_nms: True
  nms_threshold: 0.5
  score_threshold: 0.05
  # Evaluation params
  eval_batch_size: 8
  eval_iou_threshold: [0.5]
  eval_score_threshold: 0.01

train_augmentation:
  aug_seed: 42

inference:
  model_name: "efficientdet"
  input_data_dir: "/Users/snjannah/Documents/workspace/life3/data/inference"
  save_output_image: True
  inference_output_path: ""
  inference_mode: "multiple"

efficientdet:
    train_annotations_path: '/users/dylanpoh/documents/aisingapore/github/data/processed/annotations_train_efficientdet.csv'
    val_annotations_path: '/users/dylanpoh/documents/aisingapore/github/data/processed/annotations_val_efficientdet.csv'
    test_annotations_path: '/users/dylanpoh/documents/aisingapore/github/data/processed/annotations_test_efficientdet.csv'
    saved_best_model: '' # model file must exist in directory referenced in snapshot-path below
    snapshot-path: './models/'
    gpu: -1
    train_backbone: 0
    snapshot: 'imagenet'
    weighted-bifpn: True
    freeze-bn: False
    freeze-backbone: False
    random-transform: False
    batch_size: 8
    epochs: 5
    steps: 100
    inference_backbone: 0
    inference_model_path: ''
    inference_confidence_cutoff: 0.3
    # parameters for anchor boxes
    anchor_box_ratios: [1, 0.5, 2]
    anchor_box_scales: [0.5, 1.0, 2.0]
    image_sizes: [512, 640, 768, 896, 1024, 1280, 1408]
  